const cbInstructions = {
    0x00: (cpu) => { cpu.cbRlc(B); cpu.m = 3 },
    0x01: (cpu) => { cpu.cbRlc(C); cpu.m = 3 },
    0x02: (cpu) => { cpu.cbRlc(D); cpu.m = 3 },
    0x03: (cpu) => { cpu.cbRlc(E); cpu.m = 3 },
    0x04: (cpu) => { cpu.cbRlc(H); cpu.m = 3 },
    0x05: (cpu) => { cpu.cbRlc(L); cpu.m = 3 },
    0x06: (cpu) => { cpu.cbRlc(_HL_); cpu.m = 5 },
    0x07: (cpu) => { cpu.cbRlc(A); cpu.m = 3 },

    0x08: (cpu) => { cpu.cbRrc(B); cpu.m = 3 },
    0x09: (cpu) => { cpu.cbRrc(C); cpu.m = 3 },
    0x0A: (cpu) => { cpu.cbRrc(D); cpu.m = 3 },
    0x0B: (cpu) => { cpu.cbRrc(E); cpu.m = 3 },
    0x0C: (cpu) => { cpu.cbRrc(H); cpu.m = 3 },
    0x0D: (cpu) => { cpu.cbRrc(L); cpu.m = 3 },
    0x0E: (cpu) => { cpu.cbRrc(_HL_); cpu.m = 5 },
    0x0F: (cpu) => { cpu.cbRrc(A); cpu.m = 3 },

    0x10: (cpu) => { cpu.cbRl(B); cpu.m = 3 },
    0x11: (cpu) => { cpu.cbRl(C); cpu.m = 3 },
    0x12: (cpu) => { cpu.cbRl(D); cpu.m = 3 },
    0x13: (cpu) => { cpu.cbRl(E); cpu.m = 3 },
    0x14: (cpu) => { cpu.cbRl(H); cpu.m = 3 },
    0x15: (cpu) => { cpu.cbRl(L); cpu.m = 3 },
    0x16: (cpu) => { cpu.cbRl(_HL_); cpu.m = 5 },
    0x17: (cpu) => { cpu.cbRl(A); cpu.m = 3 },

    0x18: (cpu) => { cpu.cbRr(B); cpu.m = 3 },
    0x19: (cpu) => { cpu.cbRr(C); cpu.m = 3 },
    0x1A: (cpu) => { cpu.cbRr(D); cpu.m = 3 },
    0x1B: (cpu) => { cpu.cbRr(E); cpu.m = 3 },
    0x1C: (cpu) => { cpu.cbRr(H); cpu.m = 3 },
    0x1D: (cpu) => { cpu.cbRr(L); cpu.m = 3 },
    0x1E: (cpu) => { cpu.cbRr(_HL_); cpu.m = 5 },
    0x1F: (cpu) => { cpu.cbRr(A); cpu.m = 3 },

    0x20: (cpu) => { cpu.cbSla(B); cpu.m = 3 },
    0x21: (cpu) => { cpu.cbSla(C); cpu.m = 3 },
    0x22: (cpu) => { cpu.cbSla(D); cpu.m = 3 },
    0x23: (cpu) => { cpu.cbSla(E); cpu.m = 3 },
    0x24: (cpu) => { cpu.cbSla(H); cpu.m = 3 },
    0x25: (cpu) => { cpu.cbSla(L); cpu.m = 3 },
    0x26: (cpu) => { cpu.cbSla(_HL_); cpu.m = 5 },
    0x27: (cpu) => { cpu.cbSla(A); cpu.m = 3 },

    0x28: (cpu) => { cpu.cbSra(B); cpu.m = 3 },
    0x29: (cpu) => { cpu.cbSra(C); cpu.m = 3 },
    0x2A: (cpu) => { cpu.cbSra(D); cpu.m = 3 },
    0x2B: (cpu) => { cpu.cbSra(E); cpu.m = 3 },
    0x2C: (cpu) => { cpu.cbSra(H); cpu.m = 3 },
    0x2D: (cpu) => { cpu.cbSra(L); cpu.m = 3 },
    0x2E: (cpu) => { cpu.cbSra(_HL_); cpu.m = 5 },
    0x2F: (cpu) => { cpu.cbSra(A); cpu.m = 3 },

    0x30: (cpu) => { cpu.cbSwap(B); cpu.m = 3 },
    0x31: (cpu) => { cpu.cbSwap(C); cpu.m = 3 },
    0x32: (cpu) => { cpu.cbSwap(D); cpu.m = 3 },
    0x33: (cpu) => { cpu.cbSwap(E); cpu.m = 3 },
    0x34: (cpu) => { cpu.cbSwap(H); cpu.m = 3 },
    0x35: (cpu) => { cpu.cbSwap(L); cpu.m = 3 },
    0x36: (cpu) => { cpu.cbSwap(_HL_); cpu.m = 5 },
    0x37: (cpu) => { cpu.cbSwap(A); cpu.m = 3 },

    0x38: (cpu) => { cpu.cbSrl(B); cpu.m = 3 },
    0x39: (cpu) => { cpu.cbSrl(C); cpu.m = 3 },
    0x3A: (cpu) => { cpu.cbSrl(D); cpu.m = 3 },
    0x3B: (cpu) => { cpu.cbSrl(E); cpu.m = 3 },
    0x3C: (cpu) => { cpu.cbSrl(H); cpu.m = 3 },
    0x3D: (cpu) => { cpu.cbSrl(L); cpu.m = 3 },
    0x3E: (cpu) => { cpu.cbSrl(_HL_); cpu.m = 5 },
    0x3F: (cpu) => { cpu.cbSrl(A); cpu.m = 3 },

    0x40: (cpu) => { cpu.cbBit(0, cpu.reg.B); cpu.m = 3 },
    0x41: (cpu) => { cpu.cbBit(0, cpu.reg.C); cpu.m = 3 },
    0x42: (cpu) => { cpu.cbBit(0, cpu.reg.D); cpu.m = 3 },
    0x43: (cpu) => { cpu.cbBit(0, cpu.reg.E); cpu.m = 3 },
    0x44: (cpu) => { cpu.cbBit(0, cpu.reg.H); cpu.m = 3 },
    0x45: (cpu) => { cpu.cbBit(0, cpu.reg.L); cpu.m = 3 },
    0x46: (cpu) => { cpu.cbBit(0, cpu.reg._HL_); cpu.m = 4 },
    0x47: (cpu) => { cpu.cbBit(0, cpu.reg.A); cpu.m = 3 },

    0x48: (cpu) => { cpu.cbBit(1, cpu.reg.B); cpu.m = 3 },
    0x49: (cpu) => { cpu.cbBit(1, cpu.reg.C); cpu.m = 3 },
    0x4A: (cpu) => { cpu.cbBit(1, cpu.reg.D); cpu.m = 3 },
    0x4B: (cpu) => { cpu.cbBit(1, cpu.reg.E); cpu.m = 3 },
    0x4C: (cpu) => { cpu.cbBit(1, cpu.reg.H); cpu.m = 3 },
    0x4D: (cpu) => { cpu.cbBit(1, cpu.reg.L); cpu.m = 3 },
    0x4E: (cpu) => { cpu.cbBit(1, cpu.reg._HL_); cpu.m = 4 },
    0x4F: (cpu) => { cpu.cbBit(1, cpu.reg.A); cpu.m = 3 },

    0x50: (cpu) => { cpu.cbBit(2, cpu.reg.B); cpu.m = 3 },
    0x51: (cpu) => { cpu.cbBit(2, cpu.reg.C); cpu.m = 3 },
    0x52: (cpu) => { cpu.cbBit(2, cpu.reg.D); cpu.m = 3 },
    0x53: (cpu) => { cpu.cbBit(2, cpu.reg.E); cpu.m = 3 },
    0x54: (cpu) => { cpu.cbBit(2, cpu.reg.H); cpu.m = 3 },
    0x55: (cpu) => { cpu.cbBit(2, cpu.reg.L); cpu.m = 3 },
    0x56: (cpu) => { cpu.cbBit(2, cpu.reg._HL_); cpu.m = 4 },
    0x57: (cpu) => { cpu.cbBit(2, cpu.reg.A); cpu.m = 3 },

    0x58: (cpu) => { cpu.cbBit(3, cpu.reg.B); cpu.m = 3 },
    0x59: (cpu) => { cpu.cbBit(3, cpu.reg.C); cpu.m = 3 },
    0x5A: (cpu) => { cpu.cbBit(3, cpu.reg.D); cpu.m = 3 },
    0x5B: (cpu) => { cpu.cbBit(3, cpu.reg.E); cpu.m = 3 },
    0x5C: (cpu) => { cpu.cbBit(3, cpu.reg.H); cpu.m = 3 },
    0x5D: (cpu) => { cpu.cbBit(3, cpu.reg.L); cpu.m = 3 },
    0x5E: (cpu) => { cpu.cbBit(3, cpu.reg._HL_); cpu.m = 4 },
    0x5F: (cpu) => { cpu.cbBit(3, cpu.reg.A); cpu.m = 3 },

    0x60: (cpu) => { cpu.cbBit(4, cpu.reg.B); cpu.m = 3 },
    0x61: (cpu) => { cpu.cbBit(4, cpu.reg.C); cpu.m = 3 },
    0x62: (cpu) => { cpu.cbBit(4, cpu.reg.D); cpu.m = 3 },
    0x63: (cpu) => { cpu.cbBit(4, cpu.reg.E); cpu.m = 3 },
    0x64: (cpu) => { cpu.cbBit(4, cpu.reg.H); cpu.m = 3 },
    0x65: (cpu) => { cpu.cbBit(4, cpu.reg.L); cpu.m = 3 },
    0x66: (cpu) => { cpu.cbBit(4, cpu.reg._HL_); cpu.m = 4 },
    0x67: (cpu) => { cpu.cbBit(4, cpu.reg.A); cpu.m = 3 },

    0x68: (cpu) => { cpu.cbBit(5, cpu.reg.B); cpu.m = 3 },
    0x69: (cpu) => { cpu.cbBit(5, cpu.reg.C); cpu.m = 3 },
    0x6A: (cpu) => { cpu.cbBit(5, cpu.reg.D); cpu.m = 3 },
    0x6B: (cpu) => { cpu.cbBit(5, cpu.reg.E); cpu.m = 3 },
    0x6C: (cpu) => { cpu.cbBit(5, cpu.reg.H); cpu.m = 3 },
    0x6D: (cpu) => { cpu.cbBit(5, cpu.reg.L); cpu.m = 3 },
    0x6E: (cpu) => { cpu.cbBit(5, cpu.reg._HL_); cpu.m = 4 },
    0x6F: (cpu) => { cpu.cbBit(5, cpu.reg.A); cpu.m = 3 },

    0x70: (cpu) => { cpu.cbBit(6, cpu.reg.B); cpu.m = 3 },
    0x71: (cpu) => { cpu.cbBit(6, cpu.reg.C); cpu.m = 3 },
    0x72: (cpu) => { cpu.cbBit(6, cpu.reg.D); cpu.m = 3 },
    0x73: (cpu) => { cpu.cbBit(6, cpu.reg.E); cpu.m = 3 },
    0x74: (cpu) => { cpu.cbBit(6, cpu.reg.H); cpu.m = 3 },
    0x75: (cpu) => { cpu.cbBit(6, cpu.reg.L); cpu.m = 3 },
    0x76: (cpu) => { cpu.cbBit(6, cpu.reg._HL_); cpu.m = 4 },
    0x77: (cpu) => { cpu.cbBit(6, cpu.reg.A); cpu.m = 3 },

    0x78: (cpu) => { cpu.cbBit(7, cpu.reg.B); cpu.m = 3 },
    0x79: (cpu) => { cpu.cbBit(7, cpu.reg.C); cpu.m = 3 },
    0x7A: (cpu) => { cpu.cbBit(7, cpu.reg.D); cpu.m = 3 },
    0x7B: (cpu) => { cpu.cbBit(7, cpu.reg.E); cpu.m = 3 },
    0x7C: (cpu) => { cpu.cbBit(7, cpu.reg.H); cpu.m = 3 },
    0x7D: (cpu) => { cpu.cbBit(7, cpu.reg.L); cpu.m = 3 },
    0x7E: (cpu) => { cpu.cbBit(7, cpu.reg._HL_); cpu.m = 4 },
    0x7F: (cpu) => { cpu.cbBit(7, cpu.reg.A); cpu.m = 3 },

    0x80: (cpu) => { cpu.cbRes(0, B); cpu.m = 3 },
    0x81: (cpu) => { cpu.cbRes(0, C); cpu.m = 3 },
    0x82: (cpu) => { cpu.cbRes(0, D); cpu.m = 3 },
    0x83: (cpu) => { cpu.cbRes(0, E); cpu.m = 3 },
    0x84: (cpu) => { cpu.cbRes(0, H); cpu.m = 3 },
    0x85: (cpu) => { cpu.cbRes(0, L); cpu.m = 3 },
    0x86: (cpu) => { cpu.cbRes(0, _HL_); cpu.m = 3 },
    0x87: (cpu) => { cpu.cbRes(0, A); cpu.m = 3 },

    0x88: (cpu) => { cpu.cbRes(1, B); cpu.m = 3 },
    0x89: (cpu) => { cpu.cbRes(1, C); cpu.m = 3 },
    0x8A: (cpu) => { cpu.cbRes(1, D); cpu.m = 3 },
    0x8B: (cpu) => { cpu.cbRes(1, E); cpu.m = 3 },
    0x8C: (cpu) => { cpu.cbRes(1, H); cpu.m = 3 },
    0x8D: (cpu) => { cpu.cbRes(1, L); cpu.m = 3 },
    0x8E: (cpu) => { cpu.cbRes(1, _HL_); cpu.m = 3 },
    0x8F: (cpu) => { cpu.cbRes(1, A); cpu.m = 3 },

    0x90: (cpu) => { cpu.cbRes(2, B); cpu.m = 3 },
    0x91: (cpu) => { cpu.cbRes(2, C); cpu.m = 3 },
    0x92: (cpu) => { cpu.cbRes(2, D); cpu.m = 3 },
    0x93: (cpu) => { cpu.cbRes(2, E); cpu.m = 3 },
    0x94: (cpu) => { cpu.cbRes(2, H); cpu.m = 3 },
    0x95: (cpu) => { cpu.cbRes(2, L); cpu.m = 3 },
    0x96: (cpu) => { cpu.cbRes(2, _HL_); cpu.m = 5 },
    0x97: (cpu) => { cpu.cbRes(2, A); cpu.m = 3 },

    0x98: (cpu) => { cpu.cbRes(3, B); cpu.m = 3 },
    0x99: (cpu) => { cpu.cbRes(3, C); cpu.m = 3 },
    0x9A: (cpu) => { cpu.cbRes(3, D); cpu.m = 3 },
    0x9B: (cpu) => { cpu.cbRes(3, E); cpu.m = 3 },
    0x9C: (cpu) => { cpu.cbRes(3, H); cpu.m = 3 },
    0x9D: (cpu) => { cpu.cbRes(3, L); cpu.m = 3 },
    0x9E: (cpu) => { cpu.cbRes(3, _HL_); cpu.m = 5 },
    0x9F: (cpu) => { cpu.cbRes(3, A); cpu.m = 3 },

    0xA0: (cpu) => { cpu.cbRes(4, B); cpu.m = 3 },
    0xA1: (cpu) => { cpu.cbRes(4, C); cpu.m = 3 },
    0xA2: (cpu) => { cpu.cbRes(4, D); cpu.m = 3 },
    0xA3: (cpu) => { cpu.cbRes(4, E); cpu.m = 3 },
    0xA4: (cpu) => { cpu.cbRes(4, H); cpu.m = 3 },
    0xA5: (cpu) => { cpu.cbRes(4, L); cpu.m = 3 },
    0xA6: (cpu) => { cpu.cbRes(4, _HL_); cpu.m = 3 },
    0xA7: (cpu) => { cpu.cbRes(4, A); cpu.m = 3 },

    0xA8: (cpu) => { cpu.cbRes(5, B); cpu.m = 3 },
    0xA9: (cpu) => { cpu.cbRes(5, C); cpu.m = 3 },
    0xAA: (cpu) => { cpu.cbRes(5, D); cpu.m = 3 },
    0xAB: (cpu) => { cpu.cbRes(5, E); cpu.m = 3 },
    0xAC: (cpu) => { cpu.cbRes(5, H); cpu.m = 3 },
    0xAD: (cpu) => { cpu.cbRes(5, L); cpu.m = 3 },
    0xAE: (cpu) => { cpu.cbRes(5, _HL_); cpu.m = 3 },
    0xAF: (cpu) => { cpu.cbRes(5, A); cpu.m = 3 },

    0xB0: (cpu) => { cpu.cbRes(6, B); cpu.m = 3 },
    0xB1: (cpu) => { cpu.cbRes(6, C); cpu.m = 3 },
    0xB2: (cpu) => { cpu.cbRes(6, D); cpu.m = 3 },
    0xB3: (cpu) => { cpu.cbRes(6, E); cpu.m = 3 },
    0xB4: (cpu) => { cpu.cbRes(6, H); cpu.m = 3 },
    0xB5: (cpu) => { cpu.cbRes(6, L); cpu.m = 3 },
    0xB6: (cpu) => { cpu.cbRes(6, _HL_); cpu.m = 5 },
    0xB7: (cpu) => { cpu.cbRes(6, A); cpu.m = 3 },

    0xB8: (cpu) => { cpu.cbRes(7, B); cpu.m = 3 },
    0xB9: (cpu) => { cpu.cbRes(7, C); cpu.m = 3 },
    0xBA: (cpu) => { cpu.cbRes(7, D); cpu.m = 3 },
    0xBB: (cpu) => { cpu.cbRes(7, E); cpu.m = 3 },
    0xBC: (cpu) => { cpu.cbRes(7, H); cpu.m = 3 },
    0xBD: (cpu) => { cpu.cbRes(7, L); cpu.m = 3 },
    0xBE: (cpu) => { cpu.cbRes(7, _HL_); cpu.m = 5 },
    0xBF: (cpu) => { cpu.cbRes(7, A); cpu.m = 3 },

    0xC0: (cpu) => { cpu.cbSet(0, B); cpu.m = 3 },
    0xC1: (cpu) => { cpu.cbSet(0, C); cpu.m = 3 },
    0xC2: (cpu) => { cpu.cbSet(0, D); cpu.m = 3 },
    0xC3: (cpu) => { cpu.cbSet(0, E); cpu.m = 3 },
    0xC4: (cpu) => { cpu.cbSet(0, H); cpu.m = 3 },
    0xC5: (cpu) => { cpu.cbSet(0, L); cpu.m = 3 },
    0xC6: (cpu) => { cpu.cbSet(0, _HL_); cpu.m = 3 },
    0xC7: (cpu) => { cpu.cbSet(0, A); cpu.m = 3 },

    0xC8: (cpu) => { cpu.cbSet(1, B); cpu.m = 3 },
    0xC9: (cpu) => { cpu.cbSet(1, C); cpu.m = 3 },
    0xCA: (cpu) => { cpu.cbSet(1, D); cpu.m = 3 },
    0xCB: (cpu) => { cpu.cbSet(1, E); cpu.m = 3 },
    0xCC: (cpu) => { cpu.cbSet(1, H); cpu.m = 3 },
    0xCD: (cpu) => { cpu.cbSet(1, L); cpu.m = 3 },
    0xCE: (cpu) => { cpu.cbSet(1, _HL_); cpu.m = 3 },
    0xCF: (cpu) => { cpu.cbSet(1, A); cpu.m = 3 },

    0xD0: (cpu) => { cpu.cbSet(2, B); cpu.m = 3 },
    0xD1: (cpu) => { cpu.cbSet(2, C); cpu.m = 3 },
    0xD2: (cpu) => { cpu.cbSet(2, D); cpu.m = 3 },
    0xD3: (cpu) => { cpu.cbSet(2, E); cpu.m = 3 },
    0xD4: (cpu) => { cpu.cbSet(2, H); cpu.m = 3 },
    0xD5: (cpu) => { cpu.cbSet(2, L); cpu.m = 3 },
    0xD6: (cpu) => { cpu.cbSet(2, _HL_); cpu.m = 5 },
    0xD7: (cpu) => { cpu.cbSet(2, A); cpu.m = 3 },

    0xD8: (cpu) => { cpu.cbSet(3, B); cpu.m = 3 },
    0xD9: (cpu) => { cpu.cbSet(3, C); cpu.m = 3 },
    0xDA: (cpu) => { cpu.cbSet(3, D); cpu.m = 3 },
    0xDB: (cpu) => { cpu.cbSet(3, E); cpu.m = 3 },
    0xDC: (cpu) => { cpu.cbSet(3, H); cpu.m = 3 },
    0xDD: (cpu) => { cpu.cbSet(3, L); cpu.m = 3 },
    0xDE: (cpu) => { cpu.cbSet(3, _HL_); cpu.m = 5 },
    0xDF: (cpu) => { cpu.cbSet(3, A); cpu.m = 3 },

    0xE0: (cpu) => { cpu.cbSet(4, B); cpu.m = 3 },
    0xE1: (cpu) => { cpu.cbSet(4, C); cpu.m = 3 },
    0xE2: (cpu) => { cpu.cbSet(4, D); cpu.m = 3 },
    0xE3: (cpu) => { cpu.cbSet(4, E); cpu.m = 3 },
    0xE4: (cpu) => { cpu.cbSet(4, H); cpu.m = 3 },
    0xE5: (cpu) => { cpu.cbSet(4, L); cpu.m = 3 },
    0xE6: (cpu) => { cpu.cbSet(4, _HL_); cpu.m = 3 },
    0xE7: (cpu) => { cpu.cbSet(4, A); cpu.m = 3 },

    0xE8: (cpu) => { cpu.cbSet(5, B); cpu.m = 3 },
    0xE9: (cpu) => { cpu.cbSet(5, C); cpu.m = 3 },
    0xEA: (cpu) => { cpu.cbSet(5, D); cpu.m = 3 },
    0xEB: (cpu) => { cpu.cbSet(5, E); cpu.m = 3 },
    0xEC: (cpu) => { cpu.cbSet(5, H); cpu.m = 3 },
    0xED: (cpu) => { cpu.cbSet(5, L); cpu.m = 3 },
    0xEE: (cpu) => { cpu.cbSet(5, _HL_); cpu.m = 3 },
    0xEF: (cpu) => { cpu.cbSet(5, A); cpu.m = 3 },

    0xF0: (cpu) => { cpu.cbSet(6, B); cpu.m = 3 },
    0xF1: (cpu) => { cpu.cbSet(6, C); cpu.m = 3 },
    0xF2: (cpu) => { cpu.cbSet(6, D); cpu.m = 3 },
    0xF3: (cpu) => { cpu.cbSet(6, E); cpu.m = 3 },
    0xF4: (cpu) => { cpu.cbSet(6, H); cpu.m = 3 },
    0xF5: (cpu) => { cpu.cbSet(6, L); cpu.m = 3 },
    0xF6: (cpu) => { cpu.cbSet(6, _HL_); cpu.m = 5 },
    0xF7: (cpu) => { cpu.cbSet(6, A); cpu.m = 3 },

    0xF8: (cpu) => { cpu.cbSet(7, B); cpu.m = 3 },
    0xF9: (cpu) => { cpu.cbSet(7, C); cpu.m = 3 },
    0xFA: (cpu) => { cpu.cbSet(7, D); cpu.m = 3 },
    0xFB: (cpu) => { cpu.cbSet(7, E); cpu.m = 3 },
    0xFC: (cpu) => { cpu.cbSet(7, H); cpu.m = 3 },
    0xFD: (cpu) => { cpu.cbSet(7, L); cpu.m = 3 },
    0xFE: (cpu) => { cpu.cbSet(7, _HL_); cpu.m = 5 },
    0xFF: (cpu) => { cpu.cbSet(7, A); cpu.m = 3 },
}

export default cbInstructions;